# Generated by Django 2.1.7 on 2019-03-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
