# Generated by Django 2.1.7 on 2019-03-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='user',
        ),
    ]
