# Generated by Django 2.1.7 on 2019-03-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190327_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='debt_payments',
            new_name='Debt_Payments_Each_Month',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='housing_cost',
            new_name='Housing_Cost_Per_Month',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='income',
            new_name='Income',
        ),
    ]
