# Generated by Django 2.1.7 on 2019-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190327_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Country',
            field=models.CharField(choices=[('CANADA', 'Canada'), ('MEXICO', 'Mexico'), ('UNITED_STATES', 'United States of America')], default='UNITED_STATES', max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Income_Per_Year',
            field=models.BooleanField(),
        ),
    ]
