# Generated by Django 2.1.7 on 2019-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190327_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Debt_Payments_Each_Month',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Housing_Cost_Per_Month',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Income_Per_Year',
            field=models.CharField(max_length=15),
        ),
    ]
