# Generated by Django 2.1.7 on 2019-04-10 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20190327_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(choices=[('CANADA', 'Canada'), ('MEXICO', 'Mexico'), ('UNITED_STATES', 'United States of America')], default='UNITED_STATES', max_length=100)),
                ('Income_Per_Year', models.CharField(max_length=15)),
                ('Housing_Cost_Per_Month', models.CharField(max_length=15)),
                ('Debt_Payments_Each_Month', models.CharField(max_length=15)),
                ('Purchasing_A_Home', models.BooleanField(default=False)),
                ('Getting_Married', models.BooleanField(default=False)),
                ('Graduating_College', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
