# Generated by Django 2.1.7 on 2019-04-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190409_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedbudget',
            name='Alcohol',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Auto_and_Transport',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Eating_Out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Education',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Gas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Gifts_and_Donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Groceries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Health_and_Fitness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Housing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Personal_Care',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailedbudget',
            name='Pets',
            field=models.IntegerField(default=0),
        ),
    ]
