# Generated by Django 2.1.7 on 2019-04-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190410_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedbudget',
            name='Entertainment',
            field=models.IntegerField(default=0),
        ),
    ]
