# Generated by Django 2.1.7 on 2019-04-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_detailedbudget_entertainment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Debt_Payments_Each_Month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Housing_Cost_Per_Month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Income_Per_Year',
            field=models.IntegerField(default=0),
        ),
    ]
