# Generated by Django 2.1.7 on 2019-04-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190410_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Alcohol',
            new_name='Food',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Auto_and_Transport',
            new_name='Giving',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Eating_Out',
            new_name='Health',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Education',
            new_name='Insurance',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Entertainment',
            new_name='Miscellaneous',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Gas',
            new_name='Personal_Spending',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Gifts_and_Donations',
            new_name='Recreation',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Groceries',
            new_name='Saving',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Health_and_Fitness',
            new_name='Transportation',
        ),
        migrations.RenameField(
            model_name='detailedbudget',
            old_name='Personal_Care',
            new_name='Utilities',
        ),
        migrations.RemoveField(
            model_name='detailedbudget',
            name='Pets',
        ),
    ]
