# Generated by Django 2.1.7 on 2019-04-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190410_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='Debt_Payments_Each_Month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='Housing_Cost_Per_Month',
        ),
    ]
